### PR TITLE
l10n: add Chinese (China) translations for info/*.njk

### PR DESCRIPTION
**Pull request by happyaron**
This adds the Chinese (China) translations for info/*.njk, but I'm not familiar with eleventy so please help on related setups and let me know about any fixes needed, thanks!

### CODE REVIEW

**Comment by JoelMarcey** [comment]
@happyaron Hi! Thank you very much for the pull request. I am going through some older pull requests and looking/reviewing to see if they could be merged now. Many changes to the site has happened since this PR was opened, so the translation text here may be out of date. I am going to close this PR to clear our queue a bit. 

That said, if you feel as if your PR still applies, please feel free to reopen, reword, rebase and we can look at a Netlify preview to see if everything works. Thanks!

**Comment by JoelMarcey** [comment]
I will say too that we will probably consider a more broader i18n strategy for the site in the future as opposed to translating specific pages.

**Comment by happyaron** [comment]
> I will say too that we will probably consider a more broader i18n strategy for the site in the future as opposed to translating specific pages.

It would be great to make the translations available with some more popular ways - like using the gettext system, or anything that can make use of a web translation platform.

**Comment by JoelMarcey** [comment]
In the past, I have had success with CrowdIn.

**Pull request closed without merging**
