### PR TITLE
Update markdown in statement-on-global-regulations.md

### PR DESCRIPTION
**Pull request by cuviper**
The footnotes and external links were not actual HTML links. I added `markdown-it-footnote` for the footnotes, and used regular markdown links for the security policy and the Linux Foundation guidance.

### CODE REVIEW

**Review by JoelMarcey — APPROVED** [review]
Cool. I was thinking of adding something like this. 

Do you want to also change a manual footnote I added for https://foundation.rust-lang.org/news/2021-11-16-news-announcing-cloud-compute-initiative/ while you are at it?

I can do in a separate pull request too. 

Either way.

**Comment by cuviper** [comment]
Sure, try that!

**Comment by JoelMarcey** [comment]
Looks good! 

Shipit!

**Review by JoelMarcey — APPROVED** [review]

**Comment by cuviper** [comment]
> Shipit!

If you're telling *me* to merge, I don't have access.

**Comment by JoelMarcey** [comment]
Oh sorry. Didn't realize that. I will merge it.

**Pull request merged**
