### PR TITLE
Meeting minutes and public packages

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**

### CODE REVIEW

**Comment by ashleygwilliams** [comment]
> I did note that the current public artifacts for some of the meetings still need to be filled in with dates of approval and emails - I don't think I currently have the raw artifacts at hand, but I also don't think it's necessary to block on that happening for this to get merged.

@Mark-Simulacrum i'm not really sure what this means?

**Review by ashleygwilliams — COMMENTED** [review]
i think this generally looks good to me. do we want to name the board meetings with month and year for the standard monthly board meeting? e.g. instead of "Board Meeting" use "May 2021 Monthly Board Meeting"

**Comment by Mark-Simulacrum** [comment]
> > I did note that the current public artifacts for some of the meetings still need to be filled in with dates of approval and emails - I don't think I currently have the raw artifacts at hand, but I also don't think it's necessary to block on that happening for this to get merged.
> 
> @Mark-Simulacrum i'm not really sure what this means?

e.g., https://github.com/rustfoundation/foundation.rust-lang.org/blob/7237de65f8970484bc820930e1db3b3aa4e642a5/static/2021-02-09-package/Exhibit%20A%20-%20Antitrust%20Policy.pdf ends with:

image

since I don't have the ability to edit the PDF file and don't have the raw file to re-generate a PDF from.

I don't think it matters but wanted to note it as a potential concern.

I think naming with month/year sounds like a great idea - I'll go ahead and make that change shortly.

**Comment by ashleygwilliams** [comment]
@Mark-Simulacrum thanks for clarifying! seems good. we should make sure to update those assets but i dont think we should block on it.

**Comment by Mark-Simulacrum** [comment]
Alright, pushed up the month/year naming.

**Review by ashleygwilliams — APPROVED** [review]
i am good with this! thanks for doing it. i might recommend rebasing on main because i think there's potentially a redundancy re the `static` dir in the `.eleventy.js` file otherwise please merge at will! are you planning on making the blogpost in a different PR?

**Comment by Mark-Simulacrum** [comment]
Yeah, I think blog post should be separate, I need to invest a bit more time into it anyway I think. Rebased this but looks like git didn't run into any trouble with the merge.

**Comment by Mark-Simulacrum** [comment]
I think I actually can't merge though after the transfer to rustfoundation so will leave to you (should probably reduce bus factor there in the future)

**Pull request merged**
