### PR TITLE
updated the x formerly twitter icon and logo

### PR DESCRIPTION
**Pull request by martcpp**
- Updated the social icon for **X formerly Twitter** from the bluebird icon to the X logo 
- Change the **X formerly Twitter** URL to have the new URL  `https://x.com/rust_foundation`

### The old site
oldrust

### the new update
NEWRUST

### CODE REVIEW

**Comment by martcpp** [comment]
@MarcoIeni @JoelMarcey

**Comment by MarcoIeni** [comment]
hi, I'm not part of the team that manages the website. However, I noticed you didn't include the X PNGs

**Comment by martcpp** [comment]
> hi, I'm not part of the team that manages the website. However, I noticed you didn't include the X PNGs

I just push that thanks for making letting me know lol, it was still in my local 📂

**Comment by MarcoIeni** [comment]
Can you align the two logos in the contact page?
Screenshot 2024-08-21 at 17 32 28

**Comment by martcpp** [comment]
> Can you align the two logos in the contact page? Screenshot 2024-08-21 at 17 32 28

Will work on it later today

**Comment by martcpp** [comment]
@MarcoIeni  done with thanks for bringing my attention to it 

> Can you align the two logos in the contact page? Screenshot 2024-08-21 at 17 32 28

done with it thanks for bringing my attention to it i didn't take that notice

**Review by MarcoIeni — APPROVED** [review]
Thanks!

**Pull request merged**
